name: sqlite_wrapper
description: A simple way to easily use the SQLite library (even in a reactive way)
version: 0.1.4
homepage: https://github.com/stefalda/sqlite_wrapper
issue_tracker: https://github.com/stefalda/sqlite_wrapper/issues

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  js: any
  sqlite3: ^2.4.0
  sqflite_common_ffi_web: ">=0.1.0-dev.1"

dev_dependencies:
  flutter_lints: ^4.0.0
  test: ^1.21.1
