name: sqlite_wrapper
description: A simple way to easily use the SQLite library (even in a reactive way)
version: 0.0.1
homepage: https://github.com/stefalda/sqlite_wrapper

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  sqlite3: ^1.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0